openapi: 3.0.3
info:
  title: Product Price API
  description: API for retrieving product prices.
  version: 1.0.0
servers:
  - url: https://hmg-api.segs.app.br
    description: Main server
paths:
  /ecommerce/assistant/product-price:
    get:
      summary: Get product prices
      description: Retrieves a list of product prices.
      parameters:
        - name: q
          in: query
          description: Search term for products.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
